#disable_system_gems

gem 'nokogiri', '>= 1.4.1'
gem 'daemon-kit', '>= 0.1.7.12'
gem 'em-http-request', '>= 0.2.6'
gem 'mime-types', '>= 1.16'
gem 'activerecord', '= 2.3.5'
gem 'pg', '>= 0.8.0'

gem "rspec", :only => :testing
gem "mocha", :only => :testing
